spring:
  profiles:
    active: ${activeprofile}
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  session:
    store-type: redis
#mybatisPlus
mybatis-plus:
  type-aliases-package: com.zhiyu.*.model.**,com.zhiyu.*.model
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
      db-config:
        table-underline: true
        field-strategy: not_empty
        db-type: mysql
        id-type: auto
      banner: false
# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: hellozhiyu0x9987ab-zqztatqbzmkdkdnnh-a
    # 令牌有效期（默认30分钟）
    expireTime: 30
