server:
  port: 9527
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30
spring:
  datasource:
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
    dynamic:
      druid:
        initial-size: 5
        max-active: 20
        min-idle: 10
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        max-evictable-idle-time-millis:
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: select 1
        filters: stat # 注意这个值和druid原生不一致，默认启动了stat,wall
        stat:
          merge-sql: true
          log-slow-sql: true
      datasource:
        master:
          username: root
          password: 123456
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://localhost:3306/zhiyu?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false

  redis:
    host: localhost
    port: 6379
    database: 10
    password: typro12346789
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-idle: 500
        min-idle: 8
        max-wait: 100
logging:
  level:
    root: INFO
    com.magicdu: DEBUG
    com.baomidou: DEBUG
    org.apache.shiro.cache.ehcache.EhCacheManager: WARN

magic:
  uploadPath: d:/static

crypto:
  charset: UTF-8
  key: 1234123412ABCDEF

api:
  encrypt:
    rsa:
      publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDtfa4T8xDHdhKZwKRYdUkgs4gaKb+j8XQBT0rmvUKDg7J+UPa/ijTByDDFflKWP0Z2NyI/fpgPONHfZkW0YBmmJIxVcF+8T9kyDJ+Tio7AybLaDVuu0YUww3NqlwfQoh19wfY5A8Ms0nJLJgq2LSWdxYwR4OYmvDRaeBYuXpDJ7QIDAQAB
      privateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAO19rhPzEMd2EpnApFh1SSCziBopv6PxdAFPSua9QoODsn5Q9r+KNMHIMMV+UpY/RnY3Ij9+mA840d9mRbRgGaYkjFVwX7xP2TIMn5OKjsDJstoNW67RhTDDc2qXB9CiHX3B9jkDwyzScksmCrYtJZ3FjBHg5ia8NFp4Fi5ekMntAgMBAAECgYAU8RcvlShunj/HpRAY6Ma5BnvC6tmGSF1VXDubmybJWAyeTN9lRneeetuqHpiDvTKma/guJyibdwQysd8Fp8+7Bk+dIfcdiW7ICtJGB/7B3sdb7FwOWzleOEJbqevBwp1qiWIu6BsPezzyb5iBoqMZkqDKFMx6/RxvEI68Uob1YQJBAP1VZLFnpyduYO8dJehr++sl5gZ+R7+nV6gXeWxueE/W3VM4ZuaOUNWgJACGIKLthifyAqp+rIvI7ChL5Hjj/UkCQQDv/ZlGgs2A0pY3UkhSfy5okvJbHwVhLDyHYI1wQvo3HPrEBzXRGnnPLLaPe2d2m0+qQUxoIFf28i25oLKmq5uFAkEAguTKYDeUUHVhtGq1GYAh6//q+FPrMoV+byWh4Xq6w1XbiZJM6LeD4L0bnQGwfz6G4MDUy88jzB4Gl1OPOz9hsQJBAMRL9OQUt0yIcy/60IcR2f7VOwDHRdouma/NjMLnNcyAmqhekWlgs4N+ujBwKrd739SNppaA5hJqEnaD97yWHxUCQQDNLfl6yT00n73twT08UqK+nQFnubwklND6LiXZ/cPY5FR1ueYvC3CvT+yOQfhV4kLUUmuPHxj0NhR6T9H+4cge
      frontPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDtfa4T8xDHdhKZwKRYdUkgs4gaKb+j8XQBT0rmvUKDg7J+UPa/ijTByDDFflKWP0Z2NyI/fpgPONHfZkW0YBmmJIxVcF+8T9kyDJ+Tio7AybLaDVuu0YUww3NqlwfQoh19wfY5A8Ms0nJLJgq2LSWdxYwR4OYmvDRaeBYuXpDJ7QIDAQAB
    aes:
      password: 19fdaac296d84defa43e7f29
      iv: magicdu23souniub