server:
  port: 9527
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30
spring:
  datasource:
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
    dynamic:
      druid:
        initial-size: 5
        max-active: 20
        min-idle: 10
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        max-evictable-idle-time-millis:
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: select 1
        filters: stat # 注意这个值和druid原生不一致，默认启动了stat,wall
        stat:
          merge-sql: true
          log-slow-sql: true
      datasource:
        master:
          username: ${MYSQLUSERNAME}
          password: ${MYSQLPASSWORD}
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          url: jdbc:log4jdbc:mysql://${MYSQLSERVER}:${MYSQLPORT}/${DATABASENAME}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false

  redis:
    host: ${REDISSERVER}
    port: ${REDISPORT}
    database: 0
    password: ${REDISPASSWORD}
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-idle: 500
        min-idle: 8
        max-wait: 100
logging:
  level:
    root: INFO
    com.magicdu: DEBUG
    com.baomidou: DEBUG
    org.apache.shiro.cache.ehcache.EhCacheManager: WARN

magic:
  uploadPath: /root/static
